Get http://localhost:3000/songs.json

###

Get http://localhost:3000/songs/1.json

###

Post http://localhost:3000/songs.json
Content-Type: application/json

{
"title": "Waiting On the World to Change",
"album": "Continuum",
"artist": "John Mayer",
"year": "2006" 
}

###

PATCH http://localhost:3000/songs/1.json
Content-Type: application/json

{
 "year": 2005
}

###

DELETE http://localhost:3000/songs/1.json